### ISSUE TITLE
Não consigo abrir fichas de Personagem / Mestre

### ISSUE THREAD

**Issue by ghost** [mclemente/fvtt-trpg#7]
Boa noite! Estou tentando montar minha mesa de Império de Jade pelo Foundry e encontrei o seu módulo, eu consigo criar itens tranquilamente e vejo as configurações de Tormenta e Império de Jade nas configurações, mas quando eu crio qualquer personagem (seja do jogador ou do mestre), nada acontece. 
![image](https://github.com/mclemente/fvtt-trpg/assets/101234746/c951fc47-94d9-4f10-80e1-1c86a096659d)

Eu sou o Gamemaster então claro que tenho as permissões para abrir as fichas independente de quem crie, e eu vejo nas configurações do Sheet que tem as informações do Império de Jade direitinho.
![image](https://github.com/mclemente/fvtt-trpg/assets/101234746/ba0b80ee-29fc-4e31-8cf1-30a65ded3183)

Pode me ajudar com isso por favor? Tava doido pra mestrar minha campanha de IDJ pelo Foundry 🫠
Valeu!! :)

**Comment by endreuDev** [comment]
Pô muito obrigado por não me ajudar :) Um excelente dia

**Comment by mclemente** [comment]
![image](https://github.com/mclemente/fvtt-trpg/assets/5288872/9597eddc-ce86-4826-9e97-6b0a3ec92099)

Ninguém mandou atualizar pro V12 quando o sistema não tava verificado, né, imbecil? 🤡
