### ISSUE TITLE
Ficha não carregando apropriadamente

### ISSUE THREAD

**Issue by ghost** [mclemente/fvtt-trpg#8]
Bem como você foi bem educado em avisar no último issue que o problema foi resolvido e não simplesmente fechou o caso sem nem me dar uma resposta me largando pra descobrir sozinho se já estava funcionando ou não, abri o Foundry pra testar e incrivelmente, existem problemas. Não consigo editar nenhum desses valores aqui pra adicionar idiomas, imunidades, mas tudo bem né...
![image](https://github.com/mclemente/fvtt-trpg/assets/101234746/3238de36-9e79-4a85-8b67-9e91adf8f438)

Muito fofo você também chamar de imbecil o cara que fez uma brincadeira devido a sua falta de educação, não se preocupa em corrigir esse problema rápido não porque se for pra usar o serviço de um babaca, prefiro aprender sozinho pra tentar fazer algo melhor e mais bonito :)

Excelente dia 🥰
            

  ![image](https://github.com/mclemente/fvtt-trpg/assets/5288872/9597eddc-ce86-4826-9e97-6b0a3ec92099)

Ninguém mandou atualizar pro V12 quando o sistema não tava verificado, né, imbecil? 🤡

_Originally posted by @mclemente in https://github.com/mclemente/fvtt-trpg/issues/7#issuecomment-2183440819_

**Comment by mclemente** [comment]
> Muito fofo você também chamar de imbecil o cara que fez uma brincadeira devido a sua falta de educação

Brincadeira você faz com seus amigos, e se fosse brincadeira mesmo, você não teria apagado a mensagem depois que viu que fez merda 🤡

Tem "dev" no username só pra fazer pose, pq não sabe usar a porra do Github, aprende aí:
- O commit fechou a issue sozinho.
- Eu recebo email de respostas nos meus repos, mesmo se você apagar a mensagem depois.

E outra, eu não tenho obrigação de te responder, não. Se você tava tão interessado, não custava nada abrir o repo pra ver que eu tinha acabado de lançar uma versão nova.
Já fechei um monte de issue nesse site sem falar nada e você é o primeiro usuário fanfarrão, ou melhor, "dev".

> não se preocupa em corrigir esse problema rápido não porque se for pra usar o serviço

Serviço? Não recebi Pix de você, não. Eu te fiz um favor.

> prefiro aprender sozinho pra tentar fazer algo melhor e mais bonito :)

Mermão, você é um ingrato que ainda por cima estuda na Estácio, se manca. Carente do caralho.
